{% set name = "sphinx-autodoc-typehints" %}
{% set version = "2.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx_autodoc_typehints-{{ version }}.tar.gz
  sha256: e743512da58b67a06579a1462798a6907664ab77460758a43234adeac350afbf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling >=1.25
    - hatch-vcs >=0.4
    - pip
  run:
    - python >=3.10
    - sphinx >=8.0.2

test:
  imports:
    - sphinx_autodoc_typehints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sphinx-autodoc-typehints/
  summary: Type hints (PEP 484) support for the Sphinx autodoc extension
  dev_url: https://github.com/tox-dev/sphinx-autodoc-typehints
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
