{% set version = "1.7.0" %}

package:
  name: sphinx-autodoc-typehints
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx-autodoc-typehints/sphinx-autodoc-typehints-{{ version }}.tar.gz
  sha256: 8eb1e2bc248d316a9faeca086c6133623f6d45770e342738158249356989b95c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3
    - pip
    - sphinx >=1.4

  run:
    - python >=3
    - sphinx >=1.4

test:
  imports:
    - sphinx_autodoc_typehints

about:
  home: https://github.com/agronholm/sphinx-autodoc-typehints
  license: MIT
  license_file: LICENSE
  summary: 'Type hints (PEP 484) support for the Sphinx autodoc extension'
  license_family: MIT

extra:
  recipe-maintainers:
    - kwilcox
