{% set python_min = "3.10" %}
{% set name = "sphinx-autodoc-typehints" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx_autodoc_typehints-{{ version }}.tar.gz
  sha256: b9b40dd15dee54f6f810c924f863f9cf1c54f9f3265c495140ea01be7f44fa55

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.25
    - hatch-vcs >=0.4
    - pip
  run:
    - python >={{ python_min }}
    - sphinx >=8.1.3

test:
  imports:
    - sphinx_autodoc_typehints
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sphinx-autodoc-typehints/
  summary: Type hints (PEP 484) support for the Sphinx autodoc extension
  dev_url: https://github.com/tox-dev/sphinx-autodoc-typehints
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
