{% set name = "sphinx-autodoc-typehints" %}
{% set version = "1.25.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx_autodoc_typehints-{{ version }}.tar.gz
  sha256: f305bd5b763dbf0489cb6d68e8f7ce9ab520c2bcc480544e751d7a41b1c92c92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.18
    - hatch-vcs >=0.3
    - pip
  run:
    - python >=3.8
    - sphinx >=7.1.2

test:
  imports:
    - sphinx_autodoc_typehints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sphinx-autodoc-typehints/
  summary: Type hints (PEP 484) support for the Sphinx autodoc extension
  dev_url: https://github.com/tox-dev/sphinx-autodoc-typehints
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
