{% set name = "sphinx-autodoc-typehints" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx_autodoc_typehints-{{ version }}.tar.gz
  sha256: 8f8281654ddf5709875429b7120d367f4edee39a131e13d5806e4f779a81bf0f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling >=1.24
    - hatch-vcs >=0.4
    - pip
  run:
    - python >=3.9
    - sphinx >=8.0.2

test:
  imports:
    - sphinx_autodoc_typehints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sphinx-autodoc-typehints/
  summary: Type hints (PEP 484) support for the Sphinx autodoc extension
  dev_url: https://github.com/tox-dev/sphinx-autodoc-typehints
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
