schema_version: 1

context:
  python_min: "3.12"
  version: "3.13.5"

package:
  name: sphinx-autodoc-typehints
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sphinx-autodoc-typehints/sphinx_autodoc_typehints-${{ version }}.tar.gz
  sha256: d33a3651a2cec3e2562b456cd92de61d820922a7710eeb2081636696b7f80dd7

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatch-vcs >=0.5
    - hatchling >=1.29
    - pip
  run:
    - python >=${{ python_min }}
    - sphinx >=9.1

tests:
  - python:
      imports:
        - sphinx_autodoc_typehints
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Type hints (PEP 484) support for the Sphinx autodoc extension
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tox-dev/sphinx-autodoc-typehints
  repository: https://github.com/tox-dev/sphinx-autodoc-typehints

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
